'use strict';
let captureProposal=null,capturePending=null,captureWorking=false;
const captureStorage='atlas.capture.pending.v1';
$('capture-zone').textContent='Deadline and reminder timezone: '+zone+'. Ambiguous local times use the earlier instant.';
$('capture-with-reminder').onchange=()=>{$('capture-reminder-fields').hidden=!$('capture-with-reminder').checked;$('capture-at').required=$('capture-with-reminder').checked;};
function captureInput(){const reminder=$('capture-with-reminder').checked;return {title:$('capture-title').value,details:$('capture-details').value,due_at:deadlineValue($('capture-due').value),reminder_at:reminder?deadlineValue($('capture-at').value):'',reminder_title:reminder?$('capture-reminder-title').value:'',timezone:reminder?zone:'',repeat:reminder?$('capture-repeat').value:''};}
function captureControls(){$('capture-form').hidden=!!capturePending||!$('capture-saved').hidden;const locked=captureWorking||!!capturePending||!$('capture-saved').hidden;$('capture-fields').disabled=locked;$('capture-preview').disabled=locked;$('capture-confirm').disabled=captureWorking;$('capture-new').disabled=captureWorking;}
function showCaptureProposal(){const p=captureProposal,host=$('capture-summary');host.replaceChildren();const add=text=>{const el=document.createElement('p');el.textContent=text;host.append(el);};add('Task: '+p.input.title);if(p.input.details)add('Details: '+p.input.details);add('Deadline: '+(p.input.due_at?new Date(p.input.due_at).toLocaleString()+' ('+zone+')':'None'));if(p.input.reminder_at){add('Linked reminder: '+p.input.reminder_title);add('Remind at: '+new Date(p.input.reminder_at).toLocaleString([],{timeZone:p.input.timezone})+' ('+p.input.timezone+')');add('Repeat: '+(p.input.repeat||'Once'));}else add('No reminder.');for(const warning of p.warnings)add(warning);$('capture-proposal-json').textContent=JSON.stringify(p,null,2);$('capture-review').hidden=false;}
$('capture-form').oninput=()=>{if(!capturePending&&!captureWorking){captureProposal=null;$('capture-review').hidden=true;$('capture-message').textContent='Fields changed. Preview again before saving.';}};
$('capture-form').onsubmit=async e=>{e.preventDefault();if(captureWorking||capturePending)return;captureProposal=null;$('capture-review').hidden=true;captureWorking=true;captureControls();try{captureProposal=await api('capture/preview','POST',captureInput());showCaptureProposal();$('capture-message').textContent='Preview only. Review the task, time, timezone, and repeat before confirming.';}catch(error){$('capture-message').textContent=error.message;}finally{captureWorking=false;captureControls();}};
$('capture-confirm').onclick=async()=>{
 if(captureWorking||!captureProposal)return;
 // Persist the exact request before transmission; reload can safely retry it.
 if(!capturePending){const pending={key:crypto.randomUUID(),proposal:captureProposal};try{sessionStorage.setItem(captureStorage,JSON.stringify(pending));capturePending=pending;}catch(error){$('capture-message').textContent='The browser could not preserve this retry request. Enable session storage before confirming.';return;}}
 captureWorking=true;captureControls();$('capture-message').textContent='Saving task and reminder together…';
 try{
  const response=await fetch('/api/v1/capture/commit',{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':capturePending.key},body:JSON.stringify(capturePending.proposal.input)});
  const body=await response.json();if(!response.ok)throw new Error(body.error?.message||'Atlas could not confirm this capture.');
  $('capture-state-json').textContent=JSON.stringify({status:response.status,replayed:response.headers.get('Idempotency-Replayed'),state:body},null,2);$('api-response').textContent=$('capture-state-json').textContent;
  $('capture-saved-links').replaceChildren();const link=(text,feature,id)=>{const a=document.createElement('a');a.className='record-link';a.textContent=text;a.href='/#'+feature+'/'+id;$('capture-saved-links').append(a);};link('Open saved task','tasks',body.task_id);if(body.reminders.length)link('Open linked reminder','reminders',body.reminders[0].id);
  $('capture-saved').hidden=false;$('capture-review').hidden=true;capturePending=null;try{sessionStorage.removeItem(captureStorage);}catch{}
  $('capture-message').textContent=response.headers.get('Idempotency-Replayed')==='true'?'Original capture recovered. Nothing was duplicated. Saved state is the creation receipt; open the record for current state.':(body.reminders.length?'Saved. The task and linked reminder are ready.':'Saved. The task is ready.');
  try{await load(true);}catch{$('capture-message').textContent+=' Refresh data to reload the saved records.';}
 }catch(error){$('capture-message').textContent=error.message+' Retry this same confirmation to recover its result. Fields are locked to prevent an accidental duplicate.';$('capture-confirm').textContent='Retry same confirmation';}
 finally{captureWorking=false;captureControls();}
};
$('capture-new').onclick=()=>{captureProposal=null;capturePending=null;$('capture-form').reset();$('capture-reminder-fields').hidden=true;$('capture-at').required=false;$('capture-review').hidden=true;$('capture-saved').hidden=true;$('capture-confirm').textContent='Confirm and save';$('capture-message').textContent='Nothing is saved until you confirm.';captureControls();};
try{const pending=JSON.parse(sessionStorage.getItem(captureStorage)||'null');if(pending){capturePending=pending;captureProposal=pending.proposal;showCaptureProposal();$('capture-confirm').textContent='Retry same confirmation';$('capture-message').textContent='An earlier confirmation may have been saved. Retry the same request to recover its result safely.';captureControls();}}catch{$('capture-message').textContent='Could not restore the pending capture. Check existing records before creating it again.';}
