'use strict';
let captureProposal=null,capturePending=null,captureWorking=false;
let captureDraftTimes={};
const captureStorage='atlas.capture.pending.v1';
$('capture-zone').textContent='Fields use your browser timezone: '+zone+'. Ambiguous local times in these fields use the earlier instant.';
$('sentence-zone').textContent='Sentence dates and times use '+zone+'. Nothing is saved until you review and confirm.';
function updateCaptureKind(){const kind=$('capture-kind').value,note=kind==='note',task=kind==='task',reminder=kind==='reminder'||(task&&$('capture-with-reminder').checked);for(const [id,visible] of [['capture-title-field',!note],['capture-before-field',task],['capture-details-field',task],['capture-due-field',task],['capture-link-field',task],['capture-reminder-fields',reminder],['capture-reminder-title-field',task]])$(id).hidden=!visible;$('capture-title').required=!note;$('capture-at').required=reminder;$('capture-note').required=note;}
$('capture-kind').onchange=updateCaptureKind;$('capture-with-reminder').onchange=updateCaptureKind;
function captureLocalTime(value){if(!value)return '';const d=new Date(value);return localDeadline(value)+':'+String(d.getSeconds()).padStart(2,'0');}
function captureDateValue(id,key){const value=$(id).value;if(!value)return '';if(captureDraftTimes[key]?.value===value)return captureDraftTimes[key].instant;const d=new Date(value);if(!Number.isFinite(d.getTime())||localDeadline(d.toISOString())!==value.slice(0,16)||(value.length>=19&&d.getSeconds()!==Number(value.slice(17,19))))throw new Error('This local time does not exist. Choose another time.');return d.toISOString();}
function captureInput(){const kind=$('capture-kind').value,reminder=kind==='reminder'||(kind==='task'&&$('capture-with-reminder').checked);return {kind,before_task_id:kind==='task'?$('capture-before').value:'',title:kind==='note'?'':$('capture-title').value,details:kind==='task'?$('capture-details').value:'',due_at:kind==='task'?captureDateValue('capture-due','due'):'',reminder_at:reminder?captureDateValue('capture-at','reminder'):'',reminder_title:reminder&&kind==='task'?$('capture-reminder-title').value:'',timezone:reminder?zone:'',repeat:reminder?$('capture-repeat').value:'',note_body:$('capture-note').value};}
function fillCaptureDraft(input){if(input.before_task_id&&!Array.from($('capture-before').options).some(o=>o.value===input.before_task_id)){const o=document.createElement('option');o.value=input.before_task_id;o.textContent='Referenced task · refresh for title';$('capture-before').append(o);}$('capture-before').value=input.before_task_id||'';$('capture-kind').value=input.kind||'task';$('capture-title').value=input.title||'';$('capture-details').value=input.details||'';$('capture-due').value=captureLocalTime(input.due_at);$('capture-at').value=captureLocalTime(input.reminder_at);captureDraftTimes={due:{value:$('capture-due').value,instant:input.due_at},reminder:{value:$('capture-at').value,instant:input.reminder_at}};$('capture-reminder-title').value=input.reminder_title||'';$('capture-repeat').value=input.repeat||'';$('capture-note').value=input.note_body||'';$('capture-with-reminder').checked=!!(input.reminder_at||input.timezone);updateCaptureKind();}
function captureControls(){const locked=captureWorking||!!capturePending||!$('capture-saved').hidden;$('capture-editor').hidden=!!capturePending||!$('capture-saved').hidden;$('sentence-form').hidden=!!capturePending||!$('capture-saved').hidden;$('capture-fields').disabled=locked;$('capture-sentence').disabled=locked;$('capture-context').disabled=locked;$('capture-lead').disabled=locked;$('sentence-interpret').disabled=locked;document.querySelectorAll('[data-example]').forEach(x=>x.disabled=locked);$('capture-preview').disabled=locked;$('capture-confirm').disabled=captureWorking;$('capture-new').disabled=captureWorking;}
function showCaptureProposal(){const p=captureProposal,host=$('capture-summary'),kind=p.input.kind||'task';host.replaceChildren();const add=text=>{const el=document.createElement('p');el.textContent=text;host.append(el);};if(kind==='task'){add('Task: '+p.input.title);if(p.input.details)add('Task details: '+p.input.details);add('Deadline: '+(p.input.due_at?new Date(p.input.due_at).toLocaleString()+' ('+zone+')':'None'));}if(p.input.before_task_id){add('Must happen before: '+(p.reference?.title||p.input.before_task_id));add(p.reference?.due_at?'Referenced task due: '+new Date(p.reference.due_at).toLocaleString():'Referenced task has no deadline. Ordering only.');add(p.input.reminder_at?'Proposed reminder timing is shown below.':'This ordering has no reminder time.');}if(p.input.reminder_at){add((kind==='task'?'Linked reminder: ':'Standalone reminder: ')+p.input.reminder_title);add('Remind at: '+new Date(p.input.reminder_at).toLocaleString([],{timeZone:p.input.timezone})+' ('+p.input.timezone+')');add('Repeat: '+(p.input.repeat||'Once'));}if(p.input.note_body){add((kind==='note'?'Standalone note: ':'Linked note: ')+p.input.note_body);if(kind!=='note')add('Note links: '+(kind==='task'?'task':'')+(kind==='task'&&p.input.reminder_at?' and ':'')+(p.input.reminder_at?'reminder':''));}for(const warning of p.warnings)add(warning);$('capture-proposal-json').textContent=JSON.stringify(p,null,2);$('capture-review').hidden=false;}
function invalidateCapture(){if(!capturePending&&!captureWorking){captureProposal=null;$('capture-review').hidden=true;$('capture-message').textContent='Fields changed. Preview again before saving.';}}
$('capture-form').oninput=()=>{invalidateCapture();$('sentence-review').hidden=true;};
$('capture-lead').onchange=()=>{invalidateCapture();$('sentence-review').hidden=true;$('capture-message').textContent='Lead time changed. Interpret again to calculate the proposed reminder.';};
$('capture-context').onchange=()=>{invalidateCapture();$('capture-before').value='';$('sentence-review').hidden=true;$('capture-message').textContent='Context changed. Interpret the sentence again to review its relationship.';};
$('capture-sentence').oninput=()=>{invalidateCapture();$('sentence-review').hidden=true;$('capture-form').reset();captureDraftTimes={};updateCaptureKind();$('capture-editor').open=false;};
$('sentence-form').onsubmit=async e=>{e.preventDefault();if(captureWorking||capturePending)return;captureProposal=null;$('capture-review').hidden=true;$('sentence-review').hidden=true;captureWorking=true;captureControls();try{const result=await api('capture/interpret','POST',{text:$('capture-sentence').value,timezone:zone,context_task_id:$('capture-context').value,reminder_lead_minutes:Number($('capture-lead').value)});$('sentence-json').textContent=JSON.stringify(result,null,2);fillCaptureDraft(result.draft);if(result.reference){const p=document.createElement('p');p.textContent='Context: '+result.reference.title+(result.reference.due_at?' · due '+new Date(result.reference.due_at).toLocaleString():' · no deadline');$('sentence-context').replaceChildren(p);}else{$('sentence-context').replaceChildren();}$('sentence-candidates').replaceChildren();for(const candidate of result.candidates||[]){if(result.status==='ready'||result.reference)break;const b=document.createElement('button');b.type='button';b.textContent='Use '+candidate.title+(candidate.due_at?' · due '+new Date(candidate.due_at).toLocaleString():'')+((result.candidates||[]).filter(t=>t.title===candidate.title).length>1?' · '+candidate.id.slice(0,8):'');b.onclick=()=>{if(captureWorking)return;let option=Array.from($('capture-context').options).find(o=>o.value===candidate.id);if(!option){option=document.createElement('option');option.value=candidate.id;option.textContent=candidate.title;$('capture-context').append(option);}$('capture-context').value=candidate.id;$('sentence-form').requestSubmit();};$('sentence-candidates').append(b);}if(result.candidates_truncated){const p=document.createElement('p');p.textContent='More matches exist. Refine the task title to narrow the list.';$('sentence-candidates').append(p);}$('sentence-assumptions').replaceChildren();$('sentence-questions').replaceChildren();for(const [id,list] of [['sentence-assumptions',result.assumptions],['sentence-questions',result.questions.map(q=>q.message)]]){for(const text of list){const li=document.createElement('li');li.textContent=text;$(id).append(li);}}$('sentence-review').hidden=result.assumptions.length===0&&result.questions.length===0;if(result.status==='ready'){captureProposal=result.proposal;showCaptureProposal();$('capture-editor').open=false;$('capture-message').textContent='Review the proposed records and times, then confirm. Nothing has been saved.';}else{$('capture-editor').open=true;$('capture-message').textContent='Clarification needed. Correct the fields below and preview, or rewrite the sentence. Nothing has been saved.';}}catch(error){$('capture-message').textContent=error.message;}finally{captureWorking=false;captureControls();}};
for(const example of document.querySelectorAll('[data-example]'))example.onclick=()=>{$('capture-sentence').value=example.dataset.example;invalidateCapture();$('sentence-review').hidden=true;$('capture-form').reset();captureDraftTimes={};updateCaptureKind();$('capture-editor').open=false;$('capture-sentence').focus();};
$('capture-form').onsubmit=async e=>{e.preventDefault();if(captureWorking||capturePending)return;captureProposal=null;$('capture-review').hidden=true;captureWorking=true;captureControls();try{captureProposal=await api('capture/preview','POST',captureInput());showCaptureProposal();$('capture-message').textContent='Preview only. Review the records, time, timezone, and repeat before confirming.';}catch(error){$('capture-message').textContent=error.message;}finally{captureWorking=false;captureControls();}};
$('capture-confirm').onclick=async()=>{
 if(captureWorking||!captureProposal)return;
 if(!capturePending){const pending={key:crypto.randomUUID(),proposal:captureProposal};try{sessionStorage.setItem(captureStorage,JSON.stringify(pending));capturePending=pending;}catch{$('capture-message').textContent='The browser could not preserve this retry request. Enable session storage before confirming.';return;}}
 captureWorking=true;captureControls();$('capture-message').textContent='Saving the proposed records together…';
 try{
  const response=await fetch('/api/v1/capture/commit',{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':capturePending.key},body:JSON.stringify(capturePending.proposal.input)});
  const body=await response.json();if(!response.ok&&body.error?.code==='capture_context_changed'){const draft=capturePending.proposal.input;sessionStorage.removeItem(captureStorage);capturePending=null;captureProposal=null;fillCaptureDraft(draft);$('capture-review').hidden=true;$('capture-editor').open=true;$('capture-message').textContent=body.error.message+' Review the reference and click Preview capture. Nothing from this confirmation was saved.';return;}if(!response.ok)throw new Error(body.error?.message||'Atlas could not confirm this capture.');
  $('capture-state-json').textContent=JSON.stringify({status:response.status,replayed:response.headers.get('Idempotency-Replayed'),state:body},null,2);$('api-response').textContent=$('capture-state-json').textContent;
  $('capture-saved-links').replaceChildren();const link=(text,feature,id)=>{const a=document.createElement('a');a.className='record-link';a.textContent=text;a.href='/#'+feature+'/'+id;$('capture-saved-links').append(a);};if(body.task_id)link('Open saved task','tasks',body.task_id);for(const reminder of body.reminders)link('Open saved reminder','reminders',reminder.id);for(const note of body.notes)link('Open saved note','notes',note.id);
  $('capture-saved').hidden=false;$('capture-review').hidden=true;capturePending=null;try{sessionStorage.removeItem(captureStorage);}catch{}
  $('capture-message').textContent=response.headers.get('Idempotency-Replayed')==='true'?'Original capture recovered. Nothing was duplicated. Open a record for current state.':'Saved. All proposed records and links are ready.';
  try{await load(true);}catch{$('capture-message').textContent+=' Refresh data to reload the saved records.';}
 }catch(error){$('capture-message').textContent=error.message+' Retry this same confirmation to recover its result. Fields are locked to prevent an accidental duplicate.';$('capture-confirm').textContent='Retry same confirmation';}
 finally{captureWorking=false;captureControls();}
};
$('capture-new').onclick=()=>{captureProposal=null;capturePending=null;captureDraftTimes={};$('capture-form').reset();$('sentence-form').reset();updateCaptureKind();$('sentence-review').hidden=true;$('capture-review').hidden=true;$('capture-saved').hidden=true;$('capture-editor').open=false;$('capture-confirm').textContent='Confirm and save';$('capture-message').textContent='Nothing is saved until you confirm.';captureControls();$('capture-sentence').focus();};
updateCaptureKind();
try{const pending=JSON.parse(sessionStorage.getItem(captureStorage)||'null');if(pending){capturePending=pending;captureProposal=pending.proposal;showCaptureProposal();$('capture-confirm').textContent='Retry same confirmation';$('capture-message').textContent='An earlier confirmation may have been saved. Retry the same request to recover its result safely.';captureControls();}}catch{$('capture-message').textContent='Could not restore the pending capture. Check existing records before creating it again.';}
