'use strict';
let providerProposal=null,providerPending=null,providerBusy=false;
const providerPendingStorage='atlas.provider.pending.v1';
function providerControls(){const locked=providerBusy||!!providerPending;$('provider-fields').disabled=locked;$('provider-preview').disabled=locked;$('provider-task-only').disabled=locked;$('provider-confirm').disabled=providerBusy;document.querySelectorAll('#provider-questions button').forEach(b=>b.disabled=locked);}
function providerInvalidate(){if(providerPending)return;providerProposal=null;$('provider-confirm').hidden=true;$('provider-summary').replaceChildren();$('provider-questions').replaceChildren();$('provider-status').textContent='Changed fields: run another mock preview.';}
$('provider-fields').oninput=providerInvalidate;
function providerBody(){const local=$('provider-at').value;let at='';if(local){const date=new Date(local);if(!Number.isFinite(date.getTime())||(captureLocalTime(date.toISOString())!==local&&!(local.length===16&&captureLocalTime(date.toISOString())===local+':00')))throw new Error('Choose a valid local time.');at=date.toISOString();}return {version:'1',request_id:crypto.randomUUID(),text:$('provider-text').value,timezone:zone,scenario:$('provider-scenario').value,context_query:$('provider-query').value,answers:{context_task_id:$('provider-context').value,reminder:$('provider-reminder').value,reminder_at:at,note:$('provider-note').value,note_body:$('provider-note-body').value}};}
function providerSummary(p){const host=$('provider-summary');host.replaceChildren();const input=p.input;for(const [label,value] of [['Type',input.kind],['Title',input.title],['Note',input.note_body],['Deadline',input.due_at],['Reminder',input.reminder_at],['Before',p.reference?.title]])if(value){const line=document.createElement('p');line.textContent=label+': '+(['Deadline','Reminder'].includes(label)?new Date(value).toLocaleString():value);host.append(line);}for(const warning of p.warnings){const line=document.createElement('p');line.textContent=warning;host.append(line);}}
async function providerPreview(){if(providerBusy||providerPending)return;providerBusy=true;providerProposal=null;$('provider-confirm').hidden=true;providerControls();try{const body=providerBody();const r=await fetch('/api/v1/providers/mock/preview',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await r.json();$('provider-trace').textContent=JSON.stringify(result,null,2);$('provider-questions').replaceChildren();$('provider-summary').replaceChildren();if(!r.ok)throw new Error(result.error?.message||'Provider request failed.');$('provider-status').textContent='MOCK · '+result.state+' · no records saved.';for(const q of result.response.questions){const section=document.createElement('section');const line=document.createElement('p');line.textContent=q.prompt;section.append(line);for(const choice of q.choices){const button=document.createElement('button');button.type='button';button.textContent=choice.label;button.onclick=()=>{const field={context_task_id:'provider-context',reminder:'provider-reminder',note:'provider-note'}[q.field];if(field){$(field).value=choice.value;providerPreview();}};section.append(button);}$('provider-questions').append(section);}if(result.proposal){providerProposal=result.proposal;providerSummary(providerProposal);$('provider-confirm').hidden=false;}}catch(e){$('provider-status').textContent=e.message;}finally{providerBusy=false;providerControls();}}
$('provider-form').onsubmit=e=>{e.preventDefault();providerPreview();};
$('provider-task-only').onclick=()=>{$('provider-scenario').value='task';$('provider-reminder').value='skip';$('provider-note').value='skip';providerPreview();};
$('provider-confirm').onclick=async()=>{if(providerBusy||(!providerProposal&&!providerPending))return;if(!providerPending){providerPending={proposal:providerProposal,key:crypto.randomUUID()};try{sessionStorage.setItem(providerPendingStorage,JSON.stringify(providerPending));}catch(e){providerPending=null;$('provider-status').textContent='Could not retain confirmation for retries. Enable browser session storage and try again.';return;}}providerBusy=true;providerControls();try{const r=await fetch('/api/v1/capture/commit',{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':providerPending.key},body:JSON.stringify(providerPending.proposal.input)});const result=await r.json();if(!r.ok)throw new Error(result.error?.message||'Confirmation failed.');$('provider-trace').textContent=JSON.stringify({provider:'mock-fixtures',saved:result,replayed:r.headers.get('Idempotency-Replayed')},null,2);$('provider-status').textContent='Saved through Atlas. The mock did not write records.';providerPending=null;providerProposal=null;sessionStorage.removeItem(providerPendingStorage);$('provider-confirm').hidden=true;await load();}catch(e){$('provider-status').textContent=e.message+' Retry the same confirmation to recover safely.';$('provider-confirm').textContent='Retry same confirmation';}finally{providerBusy=false;providerControls();}};
fetch('/api/v1/providers').then(r=>r.json()).then(v=>{$('provider-availability').textContent='Contract '+v.contract_version+' · Mock available · Jev unavailable (access and adapter pending).';}).catch(()=>{$('provider-availability').textContent='Could not read provider availability.';});
try{const pending=JSON.parse(sessionStorage.getItem(providerPendingStorage)||'null');if(pending){providerPending=pending;providerProposal=pending.proposal;providerSummary(providerProposal);$('provider-confirm').hidden=false;$('provider-confirm').textContent='Retry same confirmation';$('provider-status').textContent='Pending confirmation restored. Retry to check the saved result.';providerControls();}}catch{$('provider-status').textContent='Could not restore pending provider confirmation.';}
