'use strict';
let routingResult=null,routingProposal=null,routingPending=null,routingBusy=false;
const routingStorage='atlas.routing.pending.v1';
function routingControls(){const locked=routingBusy||!!routingPending;$('routing-inputs').disabled=locked;$('routing-fields').disabled=locked;$('routing-evaluate').disabled=locked;$('routing-preview').disabled=locked;$('routing-confirm').disabled=routingBusy;document.querySelectorAll('#routing-questions button').forEach(b=>b.disabled=locked);}
function routingInvalidate(){if(routingPending)return;routingProposal=null;$('routing-confirm').hidden=true;$('routing-summary').replaceChildren();$('routing-questions').replaceChildren();}
function routingChannel(){return routingResult?.selected_channel||$('routing-choice').value;}
function routingFieldVisibility(){const channel=routingChannel(),task=channel==='tasks',note=channel==='notes';for(const id of ['title'])$('routing-'+id+'-label').hidden=note;for(const id of ['details','due','reminder','before'])$('routing-'+id+'-label').hidden=!task;for(const id of ['at','repeat'])$('routing-'+id+'-label').hidden=note||(task&&$('routing-reminder').value!=='add');$('routing-note-label').hidden=note;$('routing-note-body-label').hidden=!note&&$('routing-note').value!=='add';}
$('routing-provider').onchange=()=>{$('routing-fixture-label').hidden=$('routing-provider').value!=='mock';};
$('routing-inputs').oninput=()=>{if(routingPending)return;routingInvalidate();routingResult=null;$('routing-channel').hidden=true;$('routing-probabilities').replaceChildren();$('routing-status').textContent='Input changed. Evaluate again.';};
$('routing-fields').oninput=()=>{routingInvalidate();routingFieldVisibility();$('routing-status').textContent='Channel fields changed. Dispatch again before confirming.';};
async function routingPost(path,body){const response=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const value=await response.json();if(!response.ok){$('routing-trace').textContent=JSON.stringify(value,null,2);throw new Error(value.error?.message||'Routing request failed.');}return value;}
$('routing-form').onsubmit=async event=>{event.preventDefault();if(routingBusy||routingPending)return;routingBusy=true;routingInvalidate();routingResult=null;$('routing-channel').hidden=true;$('routing-probabilities').replaceChildren();routingControls();try{const provider=$('routing-provider').value;const body={version:'1',request_id:crypto.randomUUID(),text:$('routing-text').value,timezone:zone,context_query:$('routing-query').value};if(provider==='mock')body.fixture=$('routing-fixture').value;routingResult=await routingPost('/api/v1/routing/'+provider+'/evaluate',body);$('routing-trace').textContent=JSON.stringify(routingResult,null,2);$('routing-status').textContent=(routingResult.mock?'MOCK fixture':'Jev')+' · '+routingResult.state+(routingResult.evaluation.cache_hit?' · cache hit, no model call':routingResult.mock?' · fixture, no model call':' · one model call')+' · no records saved.';const table=document.createElement('table'),caption=document.createElement('caption');caption.textContent='Primary action probabilities';table.append(caption);for(const [action,probability] of Object.entries(routingResult.evaluation.decision.probabilities).sort((a,b)=>b[1]-a[1])){const row=document.createElement('tr'),label=document.createElement('th'),value=document.createElement('td');label.scope='row';label.textContent=action;value.textContent=(100*probability).toFixed(1)+'%';row.append(label,value);table.append(row);}$('routing-probabilities').append(table);const hint=document.createElement('p');hint.className='meta';hint.textContent='Distribution confidence: '+routingResult.evaluation.decision.confidence+' · routing threshold: '+routingResult.policy.min_probability+' · minimum margin: '+routingResult.policy.min_margin+'. These are provisional routing thresholds, not measured accuracy.';$('routing-probabilities').append(hint);if(routingResult.state==='unsupported')return;$('routing-channel').hidden=false;$('routing-dispatch-form').hidden=false;$('routing-choice-label').hidden=routingResult.state!=='needs_clarification';$('routing-channel-title').textContent=(routingResult.selected_channel||'Choose a channel')+' · field collection';$('routing-dispatch-form').reset();$('routing-before').replaceChildren(new Option('No dependency',''));for(const record of routingResult.input.context)$('routing-before').append(new Option(record.title,record.id));routingFieldVisibility();if(routingResult.state==='routed')await routingDispatch();}catch(error){$('routing-status').textContent=error.message;}finally{routingBusy=false;routingControls();}};
function routingTime(id){const local=$(id).value;if(!local)return '';const date=new Date(local);if(!Number.isFinite(date.getTime())||(captureLocalTime(date.toISOString())!==local&&!(local.length===16&&captureLocalTime(date.toISOString())===local+':00')))throw new Error('Choose a valid local time.');return date.toISOString();}
function routingBody(){const channel=routingChannel(),task=channel==='tasks',note=channel==='notes';const fields={};if(!note)fields.title=$('routing-title').value;if(task){fields.details=$('routing-details').value;fields.due_at=routingTime('routing-due');fields.before_task_id=$('routing-before').value;}const hasReminder=channel==='reminders'||(task&&$('routing-reminder').value==='add');if(hasReminder){fields.reminder_at=routingTime('routing-at');fields.repeat=$('routing-repeat').value;}if(note||$('routing-note').value==='add')fields.note_body=$('routing-note-body').value;const body={version:'1',routing_token:routingResult.routing_token,fields};if(task)body.reminder=$('routing-reminder').value;if(!note)body.note=$('routing-note').value;if(routingResult.state==='needs_clarification'){body.channel=channel;body.reviewed_channel=true;}return body;}
function routingSummary(proposal){const host=$('routing-summary');host.replaceChildren();for(const [label,value] of [['Type',proposal.input.kind],['Title',proposal.input.title],['Deadline',proposal.input.due_at],['Reminder',proposal.input.reminder_at],['Note',proposal.input.note_body],['Before',proposal.reference?.title]])if(value){const line=document.createElement('p');line.textContent=label+': '+value;host.append(line);}for(const warning of proposal.warnings){const line=document.createElement('p');line.textContent=warning;host.append(line);}}
async function routingDispatch(){if(!routingResult)return;routingInvalidate();const result=await routingPost('/api/v1/routing/dispatch',routingBody());$('routing-trace').textContent=JSON.stringify({routing:routingResult,channel:result},null,2);$('routing-status').textContent=(routingResult.mock?'MOCK fixture':'Jev')+' → '+result.channel+' · '+result.state+' · explicit fields · no records saved.';for(const question of result.questions){const section=document.createElement('section'),line=document.createElement('p');line.textContent=question.prompt;section.append(line);for(const choice of question.choices){const button=document.createElement('button');button.type='button';button.textContent=choice.label;button.onclick=async()=>{if(routingBusy||routingPending)return;$('routing-'+question.field).value=choice.value;routingFieldVisibility();routingBusy=true;routingControls();try{await routingDispatch();}catch(error){$('routing-status').textContent=error.message;}finally{routingBusy=false;routingControls();}};section.append(button);}$('routing-questions').append(section);}if(result.proposal){routingProposal=result.proposal;routingSummary(routingProposal);$('routing-confirm').hidden=false;}}
$('routing-dispatch-form').onsubmit=async event=>{event.preventDefault();if(routingBusy||routingPending||!routingResult)return;routingBusy=true;routingControls();try{await routingDispatch();}catch(error){$('routing-status').textContent=error.message;}finally{routingBusy=false;routingControls();}};
$('routing-confirm').onclick=async()=>{if(routingBusy||(!routingProposal&&!routingPending))return;if(!routingPending){routingPending={proposal:routingProposal,key:crypto.randomUUID()};try{sessionStorage.setItem(routingStorage,JSON.stringify(routingPending));}catch{routingPending=null;$('routing-status').textContent='Enable session storage to retain safe confirmation retries.';return;}}routingBusy=true;routingControls();try{const response=await fetch('/api/v1/capture/commit',{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':routingPending.key},body:JSON.stringify(routingPending.proposal.input)});const result=await response.json();if(!response.ok)throw new Error(result.error?.message||'Confirmation failed.');$('routing-trace').textContent=JSON.stringify({saved:result,replayed:response.headers.get('Idempotency-Replayed')},null,2);$('routing-status').textContent='Saved through Atlas’s confirmed capture transaction.';routingPending=null;routingProposal=null;sessionStorage.removeItem(routingStorage);$('routing-confirm').hidden=true;$('routing-confirm').textContent='Confirm and save';await load();}catch(error){$('routing-status').textContent=error.message+' Retry the same confirmation to recover safely.';$('routing-confirm').textContent='Retry same confirmation';}finally{routingBusy=false;routingControls();}};
fetch('/api/v1/routing').then(response=>response.json()).then(result=>{const jev=result.providers.find(p=>p.id==='jev');$('routing-availability').textContent=jev.configured?'Jev key configured · access is checked only when you explicitly evaluate.':'Jev key not configured · use mock fixtures while registering. Save the key in data/ai-gateway.key and restart Atlas.';$('routing-registry').textContent=JSON.stringify(result.actions,null,2);}).catch(()=>{$('routing-availability').textContent='Could not read routing configuration.';});
try{const pending=JSON.parse(sessionStorage.getItem(routingStorage)||'null');if(pending){routingPending=pending;routingProposal=pending.proposal;$('routing-channel').hidden=false;$('routing-dispatch-form').hidden=true;routingSummary(routingProposal);$('routing-confirm').hidden=false;$('routing-confirm').textContent='Retry same confirmation';$('routing-status').textContent='Pending confirmation restored. Retry to recover the original saved result.';routingControls();}}catch{$('routing-status').textContent='Could not restore pending confirmation.';}
