package catalog

import "github.com/udbhavbalaji/Atlas/internal/kernel/events"

type Domain string

type Registry struct {
	events map[events.EventType]Domain
}

func NewRegistry() Registry {
	return Registry{events: canonicalEvents()}
}

func (r Registry) Contains(eventType events.EventType) bool {
	_, ok := r.events[eventType]
	return ok
}

func (r Registry) DomainOf(eventType events.EventType) (Domain, bool) {
	domain, ok := r.events[eventType]
	return domain, ok
}

func canonicalEvents() map[events.EventType]Domain {
	return map[events.EventType]Domain{
		"ArtifactCaptured":          "Capture",
		"ArtifactImported":          "Capture",
		"ArtifactCreated":           "Capture",
		"ArtifactDeleted":           "Capture",
		"ArtifactUpdated":           "Capture",
		"DocumentImported":          "Capture",
		"DocumentParsed":            "Capture",
		"DocumentConverted":         "Capture",
		"DocumentFailed":            "Capture",
		"ImageCaptured":             "Capture",
		"ImageImported":             "Capture",
		"ImageProcessed":            "Capture",
		"AudioRecorded":             "Capture",
		"AudioImported":             "Capture",
		"AudioTranscribed":          "Capture",
		"BrowserPageCaptured":       "Capture",
		"BrowserBookmarkCaptured":   "Capture",
		"BrowserSelectionCaptured":  "Capture",
		"CameraImageCaptured":       "Capture",
		"CameraDocumentCaptured":    "Capture",
		"EntityCreated":             "Knowledge",
		"EntityMerged":              "Knowledge",
		"EntityUpdated":             "Knowledge",
		"EntityArchived":            "Knowledge",
		"RelationshipCreated":       "Knowledge",
		"RelationshipStrengthened":  "Relationships",
		"RelationshipWeakened":      "Knowledge",
		"RelationshipRemoved":       "Knowledge",
		"ArtifactClassified":        "Knowledge",
		"TopicAssigned":             "Knowledge",
		"CategoryAssigned":          "Knowledge",
		"ConfidenceUpdated":         "Knowledge",
		"EntityExtracted":           "Knowledge",
		"KeywordExtracted":          "Knowledge",
		"SummaryGenerated":          "Knowledge",
		"MetadataExtracted":         "Knowledge",
		"MemoryCreated":             "Memory",
		"MemoryStrengthened":        "Memory",
		"MemoryForgotten":           "Memory",
		"MemoryRetrieved":           "Memory",
		"MemoryLinked":              "Memory",
		"SearchIndexed":             "Search",
		"SearchIndexUpdated":        "Search",
		"SearchCompleted":           "Search",
		"SearchFailed":              "Search",
		"PriorityChanged":           "Executive",
		"OpportunityDetected":       "Executive",
		"RiskDetected":              "Executive",
		"OpenLoopDetected":          "Executive",
		"RecommendationGenerated":   "Executive",
		"ExecutiveBriefGenerated":   "Executive",
		"ExecutiveBriefDelivered":   "Executive",
		"ResponsibilityCreated":     "Responsibilities",
		"ResponsibilityCompleted":   "Responsibilities",
		"ResponsibilityDeferred":    "Responsibilities",
		"ResponsibilityCancelled":   "Responsibilities",
		"DeadlineDetected":          "Responsibilities",
		"ReminderCreated":           "Responsibilities",
		"ReminderDismissed":         "Responsibilities",
		"ProjectCreated":            "Projects",
		"ProjectUpdated":            "Projects",
		"ProjectArchived":           "Projects",
		"ProjectPaused":             "Projects",
		"MilestoneCompleted":        "Projects",
		"DeliverableCreated":        "Projects",
		"ResearchCaptured":          "Research",
		"ResearchIndexed":           "Research",
		"ResearchLinked":            "Research",
		"ResearchSummarized":        "Research",
		"SourceVerified":            "Research",
		"ContactImported":           "Relationships",
		"PersonRecognized":          "Relationships",
		"MeetingCompleted":          "Relationships",
		"InteractionRecorded":       "Relationships",
		"RelationshipUpdated":       "Relationships",
		"LearningGoalCreated":       "Learning",
		"LessonCompleted":           "Learning",
		"CourseStarted":             "Learning",
		"CourseCompleted":           "Learning",
		"SkillImproved":             "Learning",
		"TransactionImported":       "Finance",
		"ExpenseRecorded":           "Finance",
		"IncomeRecorded":            "Finance",
		"BudgetExceeded":            "Finance",
		"SubscriptionDetected":      "Finance",
		"ProductTracked":            "Shopping",
		"PriceChanged":              "Shopping",
		"DiscountDetected":          "Shopping",
		"PurchaseRecorded":          "Shopping",
		"WishlistUpdated":           "Shopping",
		"VisaDeadlineDetected":      "Immigration",
		"ApplicationUpdated":        "Immigration",
		"RequirementSatisfied":      "Immigration",
		"DocumentExpired":           "Immigration",
		"SongPlayed":                "Media",
		"AlbumSaved":                "Media",
		"PlaylistUpdated":           "Media",
		"PodcastCompleted":          "Media",
		"BookFinished":              "Media",
		"EmbeddingGenerated":        "AI",
		"OCRCompleted":              "AI",
		"TranscriptGenerated":       "AI",
		"SemanticAnalysisCompleted": "AI",
		"ReasoningCompleted":        "AI",
		"SchedulerStarted":          "Infrastructure",
		"SchedulerStopped":          "Infrastructure",
		"WorkerStarted":             "Infrastructure",
		"WorkerStopped":             "Infrastructure",
		"ServiceRegistered":         "Infrastructure",
		"ServiceUnavailable":        "Infrastructure",
		"SynchronizationStarted":    "Synchronization",
		"SynchronizationCompleted":  "Synchronization",
		"SynchronizationFailed":     "Synchronization",
		"ConflictDetected":          "Synchronization",
		"ConflictResolved":          "Synchronization",
		"AuthenticationSucceeded":   "Security",
		"AuthenticationFailed":      "Security",
		"AuthorizationDenied":       "Security",
		"PrivacyPolicyUpdated":      "Security",
		"DataRedacted":              "Security",
		"PluginInstalled":           "Plugins",
		"PluginEnabled":             "Plugins",
		"PluginDisabled":            "Plugins",
		"PluginUpdated":             "Plugins",
		"PluginRemoved":             "Plugins",
		"PluginFailed":              "Plugins",
	}
}
